os: osx
osx_image: xcode10.1
language: swift
script: xcodebuild clean build test -project OCWeather/OCWeather.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO & xcodebuild clean build test -project OCExchange/OCExchange/OCExchange.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO & xcodebuild clean build test -project OCTranslate/OCTranslate.xcodeproj -scheme "CI" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO